# Generated by Django 2.2.7 on 2019-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_create_job_and_account_models")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="total_followers",
            field=models.IntegerField(null=True),
        )
    ]
