# Generated by Django 2.2.7 on 2019-11-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0002_add_total_followers_field_to_job_model")]

    operations = [
        migrations.AlterModelOptions(
            name="job", options={"ordering": ("screen_name",), "verbose_name": "report"}
        )
    ]
