# Generated by Django 2.2.7 on 2019-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_sort_job_model")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="celery_task_id",
            field=models.CharField(
                db_index=True, default=None, max_length=155, null=True, unique=True
            ),
        )
    ]
