# Generated by Django 3.0 on 2019-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_add_celery_task_id_field_to_job_model")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="follower_of",
            field=models.ManyToManyField(
                db_index=True, related_name="followers", to="core.Job"
            ),
        )
    ]
