# Generated by Django 3.0 on 2019-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_add_related_name_to_account_relationship")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.URLField(blank=True, default=""),
        )
    ]
